@baseUrl = http://localhost:3000


######### Rutas de autenticación #########
### Registro de un usuario nuevo
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "Usuario Prueba Yo",
  "email": "2jmalvarez@gmail.com",
  "password": "2jmalvarez@gmail.com"
}

### Inicio de sesión
# @name Auth
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "2jmalvarez@gmail.com",
  "password": "2jmalvarez@gmail.com"
}

### Almacenar el token de autenticación
@token = {{Auth.response.body.data.token}}


######### Rutas de pacientes #########

### Generar un nombre aleatorio en español utilizando un servicio externo
# @name RandomName
GET https://randomuser.me/api/?nat=es

### Crear un nuevo usuario con el nombre aleatorio generado
@randomName = {{RandomName.response.body.results[0].name.first}} {{RandomName.response.body.results[0].name.last}}
@randomGender = {{RandomName.response.body.results[0].gender}}
@randomAddress = {{RandomName.response.body.results[0].location.street.name}} {{RandomName.response.body.results[0].location.street.number}}
@randomBirthDate = {{RandomName.response.body.results[0].dob.date}}

### Crear un nuevo paciente
POST {{baseUrl}}/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "{{randomName}}",
  "birth_date":"{{randomBirthDate}}",
  "gender": "{{randomGender}}",
  "address": "{{randomAddress}}"
}

### Obtener todos los pacientes
GET {{baseUrl}}/patients
Authorization: Bearer {{token}}

### Patient ID
@patientId = fb2cb47e-1c98-4453-8941-82f56f46cec0

### Obtener un paciente por ID
GET {{baseUrl}}/patients/{{patientId}}
Authorization: Bearer {{token}}


### Obtener todas las observaciones de un paciente
GET {{baseUrl}}/patients/{{patientId}}/observations
Authorization: Bearer {{token}}


### Crear una nueva observación clínica para un paciente
POST {{baseUrl}}/patients/{{patientId}}/observations
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "code": "122345",
  "value": "178.6",
  "date": "2023-12-01T10:00:00Z",
  "status": "final",
  "category": "vital-signs",
  "components": [
    {
      "code": "heart-rate",
      "value": 172,
      "unit": "bpm"
    }
   
  ]
}
### Crear una nueva observación clínica para un paciente
POST {{baseUrl}}/patients/{{patientId}}/observations
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "code": "122345",
  "value": "178.6",
  "date": "2023-12-01T10:00:00Z",
  "status": "final",
  "category": "vital-signs"
}


# Rutas de observaciones

### Actualizar una observación existente
PUT {{baseUrl}}/observations/{{patientId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "value": "130/85",
  "unit": "mmHg"
}


### Eliminar una observación
DELETE {{baseUrl}}/observations/{{patientId}}
Authorization: Bearer {{token}}


### Observaciones Fhir

### Crear observacion Fhir
POST {{baseUrl}}/observations/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "code":"213", 
  "value":"12", 
  "date":"2024-11-29T10:00:00Z"
}
 

### Ver observacion en Fhir
GET {{baseUrl}}/observations/b96e59cf-ba79-4ef2-a7d4-c028d3344c7d/fhir
Content-Type: application/json
Authorization: Bearer {{token}}
 
 